project_id = "rokxjikofbbgmwgqowwk"

[functions.delete-user]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.process-email-notifications]
verify_jwt = false
